#!bin/bash

EXT_JSON_FILENAME=$1
aws s3 mv $EXT_JSON_PATH/$EXT_JSON_FILENAME s3://$EXT_JSON_S3_BUCKET/$EXT_JSON_FILENAME
EXT_UPLOAD_SUCCESS=$?

AN_JSON_FILENAME=$2
aws s3 mv $AN_JSON_PATH/$AN_JSON_FILENAME s3://$AN_JSON_S3_BUCKET/$AN_JSON_FILENAME
AN_UPLOAD_SUCCESS=$?

if [ $EXT_UPLOAD_SUCCESS -eq 0 ] && [ $AN_UPLOAD_SUCCESS -eq 0 ]; then
	echo "success"
else
	echo "failed"
fi
